
batch_size: 1024
num_workers: 16
data_location: './datasets/'
exp_name: None
model_home: ./model/task-vector-checkpoints
log_root_path: ./logs
cache_dir: None
openclip_cachedir: '/gscratch/efml/gamaga/.cache/open_clip'
special:
  filter_ratio: 0.7
  top_k_keep: 0.01
  top_k_remove: 0.00
  with_align: False
  scaling_coef: 0.15
  shared_only: True
  task_allocate: False

